repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: prometheus
  url: https://prometheus-community.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: cert-manager
  url: https://charts.jetstack.io
- name: gatekeeper
  url: https://open-policy-agent.github.io/gatekeeper/charts

---
helmDefaults:
  wait: true
  timeout: 1200
---
releases:
- name: ingress-nginx
  version: v1.11.5
  namespace: ingress-nginx
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  values:
    - ./config/nginx-values.yaml

- name: cert-manager
  version: v1.15.3
  chart: cert-manager/cert-manager
  namespace: cert-manager
  createNamespace: true
  values:
  - "./config/cert-manager-values.yaml"
  - global:
      leaderElection:
        namespace: cert-manager
      commonLabels:
        cost-center-label: "xyz"
  - serviceAccount:
      annotations:
        {{ requiredEnv "CERT_MANAGER_SA_ANNOTATION" }}

- name: prometheus
  version: "25.27.0"
  chart: "prometheus/prometheus"
  namespace: monitoring
  createNamespace: true
  values:
  - "./config/prometheus-values.yaml"

- name: grafana
  version: "8.4.7"
  chart: grafana/grafana
  namespace: monitoring
  values:
  - "./config/grafana-values.yaml"
  # - adminUser: {{ requiredEnv "GRAFANA_ADMIN_USER" }}
  # - adminPassword: {{ requiredEnv "GRAFANA_ADMIN_PW" }}

- name: gatekeeper
  version: v3.19.0
  namespace: monitoring
  chart: gatekeeper/gatekeeper
  values:
    - ./values/gatekeeper-values.yaml
